In [35]:
import numpy as np #1
scores = np.array([
    [85, 90, 78, 92, 88],      
    [72, 75, 80, 68, 74],  
    [95, 88, 92, 96, 90],     
    [60, 65, 70, 58, 62],      
    [88, 84, 86, 89, 87]]) 

In [36]:
scores[2] #score 3 studend all marks 

array([95, 88, 92, 96, 90])

In [5]:
scores[:, 1] # 2 subject all student marks 

array([90, 75, 88, 65, 84])

In [6]:
scores[:3, :2] # first 3 student & 2 subject marks 

array([[85, 90],
       [72, 75],
       [95, 88]])

In [7]:
scores [3:,2:]#last 2 student & last 3 subject

array([[70, 58, 62],
       [86, 89, 87]])

In [8]:
scores + 5 # add 5 marks

array([[ 90,  95,  83,  97,  93],
       [ 77,  80,  85,  73,  79],
       [100,  93,  97, 101,  95],
       [ 65,  70,  75,  63,  67],
       [ 93,  89,  91,  94,  92]])

In [12]:
scores [:,3] -10 # -10 subject 4 all student

array([82, 58, 86, 48, 79])

In [24]:
a= (scores.sum(axis=1)/5)# percentage all student
print(a)

[86.6 73.8 92.2 63.  86.8]


In [29]:
b = scores.mean(axis=1)# average score for each student across all subjects
print(b)


[86.6 73.8 92.2 63.  86.8]


In [30]:
c = scores.sum(axis=1)#total marks scored by each student
print(c)


[433 369 461 315 434]


In [31]:
d = scores.max()# the highest score in the entire array
print(d)


96


In [33]:
e = scores.mean(axis=0)# average score for each subject
print(e)


[80.  80.4 81.2 80.6 80.2]


In [34]:
f = np.argmin(ascores)#the lowest average score
print(f+1)


19
